# Generated by Django 3.1.7 on 2021-03-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='serial_number',
        ),
    ]
