# Generated by Django 3.1.7 on 2021-03-23 22:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_remove_task_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 3, 23, 15, 43, 48, 136754))),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('added_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.customer')),
            ],
        ),
    ]
