# Generated by Django 3.1.7 on 2021-03-24 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20210323_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='completed_on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 17, 30, 53, 51745)),
        ),
    ]
