# Generated by Django 3.1.7 on 2021-03-25 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20210324_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_name',
            field=models.CharField(default='No account name', max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='renewal_date',
            field=models.DateField(default=datetime.date(2021, 3, 25)),
        ),
        migrations.AddField(
            model_name='customer',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='mynote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 10, 34, 21, 431295)),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 10, 34, 21, 430295)),
        ),
    ]
