# Generated by Django 3.1.7 on 2021-03-27 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20210326_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='renewal_date',
            field=models.DateField(default=datetime.date(2021, 3, 27)),
        ),
        migrations.AlterField(
            model_name='myfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.myfield'),
        ),
        migrations.AlterField(
            model_name='myfieldvalue',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mynote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 4, 32, 0, 450193)),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 4, 32, 0, 450193)),
        ),
    ]
